#include "LocalizationManager.hpp"
#include <algorithm>
#include <iostream>

// Singleton
LocalizationManager& LocalizationManager::instance() {
    static LocalizationManager inst;
    return inst;
}

LocalizationManager::LocalizationManager() : currentLang(Language::EN) {
    loadTranslations();
}

// Set language por enum
void LocalizationManager::setLanguage(Language lang) {
    currentLang = lang;
}

// Set language por código (ex: "en", "pt")
void LocalizationManager::setLanguage(const std::string& langCode) {
    std::string code = langCode;
    std::transform(code.begin(), code.end(), code.begin(), ::tolower);
    if (code == "en") currentLang = Language::EN;
    else if (code == "pt") currentLang = Language::PT;
    else if (code == "es") currentLang = Language::ES;
    else if (code == "fr") currentLang = Language::FR;
    else if (code == "ar") currentLang = Language::AR;
    else if (code == "hi") currentLang = Language::HI;
    else if (code == "bn") currentLang = Language::BN;
    else if (code == "ru") currentLang = Language::RU;
    else if (code == "zh") currentLang = Language::ZH;
}

// Pega string traduzida
std::string LocalizationManager::getString(const std::string& key) {
    auto itLang = translations.find(currentLang);
    if (itLang != translations.end()) {
        auto itKey = itLang->second.find(key);
        if (itKey != itLang->second.end()) {
            return itKey->second;
        }
    }
    return key; // fallback: retorna a própria chave
}

// Retorna código da língua atual
std::string LocalizationManager::getLanguageCode() const {
    switch (currentLang) {
        case Language::EN: return "en";
        case Language::PT: return "pt";
        case Language::ES: return "es";
        case Language::FR: return "fr";
        case Language::AR: return "ar";
        case Language::HI: return "hi";
        case Language::BN: return "bn";
        case Language::RU: return "ru";
        case Language::ZH: return "zh";
        default: return "en";
    }
}

// Prompt para selecionar língua
std::string LocalizationManager::promptForLanguage() {
    std::cout << "Select language (en, pt, es, fr, ar, hi, bn, ru, zh): ";
    std::string code;
    std::cin >> code;
    setLanguage(code);
    return getLanguageCode();
}

void LocalizationManager::loadTranslations() {
    // =========================
    // English
    // =========================
    translations[Language::EN] = {
        {"START_MSG", "RomTrimmer++ started"},
        {"SIMULATION_MODE", "SIMULATION MODE - No files will be changed"},
        {"ANALYSIS_MODE", "ANALYSIS MODE - Only reports will be generated"},
        {"PROCESSING", "Processing: "},
        {"UNKNOWN_ROM", "Unknown ROM type, skipping..."},
        {"NO_PADDING", "No padding found"},
        {"TRIM_SUCCESS", "Trim successful: "},
        {"SAVED_SPACE", "Space recovered: "},
        {"EXEC_SUMMARY", "=== EXECUTION SUMMARY ==="},
        {"NO_INPUT", "Error: No input file or directory specified"},
        {"USAGE", "Usage:"},
        {"EXAMPLES", "Examples:"},
        {"OPTIONS", "Options:"},
        {"INPUT_HELP", "Input file(s) to process"},
        {"PATH_HELP", "Directory containing ROMs"},
        {"RECURSIVE_HELP", "Search subdirectories recursively"},
        {"OUTPUT_HELP", "Output directory for trimmed ROMs"},
        {"HELP_HELP", "Show this help message"},
        {"VERSION_HELP", "Show version information"},
        {"VERBOSE_HELP", "Verbose output"},
        {"TRY_HELP", "Try 'romtrimmer++ --help' for more information."},
        {"CRITICAL_ERROR", "Critical error: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "A powerful ROM trimming utility"},
        {"FILES_PROCESSED", "Files processed"},
        {"FILES_TRIMMED", "Files trimmed"},
        {"FILES_FAILED", "Files failed"},
        {"SPACE_RECOVERED", "Space recovered"},
        {"DETAILS_TITLE", "=== FILE DETAILS ==="},
        {"ORIGINAL_SIZE", "Original"},
        {"FINAL_SIZE", "Final"},
        {"REDUCTION", "Reduction"},
        {"ERROR_LABEL", "Error"},
        {"EMPTY_FILE", "Empty file or could not be read"},
        {"AUTO_PADDING_DETECTED", "Auto-detected padding: 0x"},
        {"UNSAFE_TRIM", "Unsafe trim: "},
        {"WARNING_FORCING_TRIM", "WARNING: Forcing trim - "},
        {"ANALYSIS", "Analysis: "},
        {"CAN_BE_REMOVED", " can be removed ("},
        {"SIMULATION_REMOVE", "Simulation: Would remove "},
        {"WRITE_FILE_ERROR", "Failed to write file"},
        {"ERROR_PROCESSING", "Error processing "},
        {"CANNOT_CREATE_OUTPUT", "Cannot create output file"},
        {"ERROR_WRITING", "Error writing: "},
        {"CANNOT_OPEN_FILE", "Cannot open file"},
        {"ERROR_READING_FILE", "Error reading file"},
        {"PATH_NOT_EXIST", "Path does not exist: "},
        {"FILES_FOUND", " file(s) found"},
        {"BACKUP_EXISTS_OVERWRITING", "Backup already exists, overwriting: "},
        {"BACKUP_CREATED", "Backup created: "},
        {"BACKUP_FAILED", "Failed to create backup: "},
        {"FINAL_SIZE_BELOW_MIN", "Final size ("},
        {"BELOW_MINIMUM_ALLOWED", ") below minimum allowed ("},
        {"CUT_TOO_AGGRESSIVE", "Cut too aggressive ("},
        {"EXCEEDS_LIMIT", "%) exceeds limit ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "File too small after cut ("},
        {"BELOW_SAFETY_MARGIN", " bytes), below safety margin"},
        {"GBA_VALIDATION_FAILED", "GBA validation failed - possible important data after cut point"},
        {"NDS_VALIDATION_FAILED", "NDS validation failed - ARM9/ARM7 offsets may be invalid"},
        {"GB_VALIDATION_FAILED", "GB/GBC validation failed - ROM structure may be compromised"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "Cut too large for unknown ROM type"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "Cut would interrupt known ROM structures"},
        {"FORCE_HELP", "Force unsafe operations"},
        {"EXAMPLE_TRIM_SINGLE", "Trim single file: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "Process directory: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "Analyze only: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "OK"},
        {"HIGH_RISK_OPERATION", "High risk operation: "},
        {"VALIDATION_EXCEPTION", "Validation exception: "},
        {"EMPTY_DATA", "Empty data provided"},
        {"LARGE_CUT_WARNING", "Large cut detected ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "Consider using --analyze first or --force if certain"},
        {"HEADER_INTEGRITY_COMPROMISED", "ROM header integrity would be compromised"},
        {"SUGGEST_BACKUP_AND_VERIFY", "Create backup and verify ROM functionality after trim"},
        {"RISK_LARGE_CUT", "Large cut ("},
        {"RISK_BELOW_RECOMMENDED", "Size below recommended minimum"},
        {"RISK_STRUCTURE_CONFLICT", "Cut would affect known data structures"},
        {"RECOMMENDATION_LOW_RISK", "Low risk operation, proceed normally"},
        {"RECOMMENDATION_MEDIUM_RISK", "Medium risk, consider using --analyze first"},
        {"RECOMMENDATION_HIGH_RISK", "High risk, use --force only if absolutely certain"},
        {"RECOMMENDATION_CRITICAL_RISK", "Critical risk, operation not recommended"},
        {"INTERRUPT_RECEIVED", "Operation interrupted by user"},
        {"SEGMENTATION_FAULT", "Segmentation fault detected"},
        {"PLEASE_REPORT_BUG", "Please report this issue at the project repository"},
        {"TERMINATION_REQUESTED", "Termination requested, cleaning up..."},
        {"LANGUAGE_SET", "Language set to"},
        {"LANGUAGE_ERROR", "Language configuration error"},
        {"FALLBACK_TO_ENGLISH", "Falling back to English"},
        {"QUICK_EXAMPLES", "Quick examples"},
        {"TROUBLESHOOTING_TIPS", "Troubleshooting tips"},
        {"CHECK_PERMISSIONS", "Check file and directory permissions"},
        {"VERIFY_INPUT_FILES", "Verify that input files are valid ROMs"},
        {"TRY_DRY_RUN_FIRST", "Try with --dry-run first to see what would happen"},
        {"REPORT_ISSUE", "Report this issue with details at the project repository"},
        {"NO_BACKUP_HELP", "Do not create backup files"},
        {"ARGUMENT_ERROR", "Argument parsing error"},
        {"INVALID_OUTPUT_DIR", "Invalid output directory"},
        {"HIGH_CUT_RATIO_WARNING", "Warning: Maximum cut ratio is very high"},
        {"SUCCESSFULLY_TRIMMED", "Successfully trimmed"},
        {"NO_CHANGES", "No changes made"},
        {"SUPPORTED_FORMATS", "Supported formats"},
        {"SAFETY_NOTES", "Safety notes"}
    };

    // =========================
    // Portuguese
    // =========================
    translations[Language::PT] = {
        {"START_MSG", "RomTrimmer++ iniciado"},
        {"SIMULATION_MODE", "MODO SIMULAÇÃO - Nenhum arquivo será alterado"},
        {"ANALYSIS_MODE", "MODO ANÁLISE - Apenas relatórios serão gerados"},
        {"PROCESSING", "Processando: "},
        {"UNKNOWN_ROM", "Tipo de ROM desconhecido, pulando..."},
        {"NO_PADDING", "Nenhum padding encontrado"},
        {"TRIM_SUCCESS", "Trim realizado: "},
        {"SAVED_SPACE", "Espaço recuperado: "},
        {"EXEC_SUMMARY", "=== RESUMO DA EXECUÇÃO ==="},
        {"NO_INPUT", "Erro: Nenhum arquivo ou diretório especificado"},
        {"USAGE", "Uso:"},
        {"EXAMPLES", "Exemplos:"},
        {"OPTIONS", "Opções:"},
        {"INPUT_HELP", "Arquivo(s) de entrada para processar"},
        {"PATH_HELP", "Diretório contendo ROMs"},
        {"RECURSIVE_HELP", "Buscar em subdiretórios recursivamente"},
        {"OUTPUT_HELP", "Diretório de saída para ROMs trimadas"},
        {"HELP_HELP", "Mostrar esta mensagem de ajuda"},
        {"VERSION_HELP", "Mostrar informação de versão"},
        {"VERBOSE_HELP", "Saída detalhada"},
        {"TRY_HELP", "Tente 'romtrimmer++ --help' para mais informações."},
        {"CRITICAL_ERROR", "Erro crítico: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "Um utilitário poderoso para trim de ROMs"},
        {"FILES_PROCESSED", "Arquivos processados"},
        {"FILES_TRIMMED", "Arquivos trimados"},
        {"FILES_FAILED", "Arquivos falhos"},
        {"SPACE_RECOVERED", "Espaço recuperado"},
        {"DETAILS_TITLE", "=== DETALHES POR ARQUIVO ==="},
        {"ORIGINAL_SIZE", "Original"},
        {"FINAL_SIZE", "Final"},
        {"REDUCTION", "Redução"},
        {"ERROR_LABEL", "ERRO"},
        {"EMPTY_FILE", "Arquivo vazio ou não pôde ser lido"},
        {"AUTO_PADDING_DETECTED", "Padding auto-detectado: 0x"},
        {"UNSAFE_TRIM", "Corte não seguro: "},
        {"WARNING_FORCING_TRIM", "AVISO: Forçando corte - "},
        {"ANALYSIS", "Análise: "},
        {"CAN_BE_REMOVED", " podem ser removidos ("},
        {"SIMULATION_REMOVE", "Simulação: Removeria "},
        {"WRITE_FILE_ERROR", "Falha ao escrever arquivo"},
        {"ERROR_PROCESSING", "Erro ao processar "},
        {"CANNOT_CREATE_OUTPUT", "Não pôde criar arquivo de saída"},
        {"ERROR_WRITING", "Erro ao escrever: "},
        {"CANNOT_OPEN_FILE", "Não pôde abrir arquivo"},
        {"ERROR_READING_FILE", "Erro ao ler arquivo"},
        {"PATH_NOT_EXIST", "Caminho não existe: "},
        {"FILES_FOUND", " arquivo(s) encontrado(s)"},
        {"BACKUP_EXISTS_OVERWRITING", "Backup já existe, sobrescrevendo: "},
        {"BACKUP_CREATED", "Backup criado: "},
        {"BACKUP_FAILED", "Falha ao criar backup: "},
        {"FINAL_SIZE_BELOW_MIN", "Tamanho final ("},
        {"BELOW_MINIMUM_ALLOWED", ") abaixo do mínimo permitido ("},
        {"CUT_TOO_AGGRESSIVE", "Corte muito agressivo ("},
        {"EXCEEDS_LIMIT", "%) excede o limite ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "Arquivo muito pequeno após corte ("},
        {"BELOW_SAFETY_MARGIN", " bytes), abaixo da margem de segurança"},
        {"GBA_VALIDATION_FAILED", "Validação GBA falhou - possíveis dados importantes após ponto de corte"},
        {"NDS_VALIDATION_FAILED", "Validação NDS falhou - offsets ARM9/ARM7 podem ser inválidos"},
        {"GB_VALIDATION_FAILED", "Validação GB/GBC falhou - estrutura ROM pode estar comprometida"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "Corte muito grande para tipo de ROM desconhecido"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "Corte interromperia estruturas conhecidas da ROM"},
        {"FORCE_HELP", "Forçar operações inseguras"},
        {"EXAMPLE_TRIM_SINGLE", "Trim de arquivo único: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "Processar diretório: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "Apenas analisar: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "OK"},
        {"HIGH_RISK_OPERATION", "Operação de alto risco: "},
        {"VALIDATION_EXCEPTION", "Exceção de validação: "},
        {"EMPTY_DATA", "Dados vazios fornecidos"},
        {"LARGE_CUT_WARNING", "Corte grande detectado ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "Considere usar --analyze primeiro ou --force se tiver certeza"},
        {"HEADER_INTEGRITY_COMPROMISED", "Integridade do cabeçalho da ROM estaria comprometida"},
        {"SUGGEST_BACKUP_AND_VERIFY", "Crie backup e verifique a funcionalidade da ROM após o trim"},
        {"RISK_LARGE_CUT", "Corte grande ("},
        {"RISK_BELOW_RECOMMENDED", "Tamanho abaixo do mínimo recomendado"},
        {"RISK_STRUCTURE_CONFLICT", "Corte afetaria estruturas de dados conhecidas"},
        {"RECOMMENDATION_LOW_RISK", "Operação de baixo risco, prossiga normalmente"},
        {"RECOMMENDATION_MEDIUM_RISK", "Risco médio, considere usar --analyze primeiro"},
        {"RECOMMENDATION_HIGH_RISK", "Alto risco, use --force apenas se absolutamente certo"},
        {"RECOMMENDATION_CRITICAL_RISK", "Risco crítico, operação não recomendada"},
        {"INTERRUPT_RECEIVED", "Operação interrompida pelo usuário"},
        {"SEGMENTATION_FAULT", "Falha de segmentação detectada"},
        {"PLEASE_REPORT_BUG", "Por favor, relate este problema no repositório do projeto"},
        {"TERMINATION_REQUESTED", "Término solicitado, limpando..."},
        {"LANGUAGE_SET", "Idioma definido para"},
        {"LANGUAGE_ERROR", "Erro de configuração de idioma"},
        {"FALLBACK_TO_ENGLISH", "Voltando para o Inglês"},
        {"QUICK_EXAMPLES", "Exemplos rápidos"},
        {"TROUBLESHOOTING_TIPS", "Dicas de solução de problemas"},
        {"CHECK_PERMISSIONS", "Verifique permissões de arquivo e diretório"},
        {"VERIFY_INPUT_FILES", "Verifique se os arquivos de entrada são ROMs válidas"},
        {"TRY_DRY_RUN_FIRST", "Tente com --dry-run primeiro para ver o que aconteceria"},
        {"REPORT_ISSUE", "Relate este problema com detalhes no repositório do projeto"},
        {"NO_BACKUP_HELP", "Não criar arquivos de backup"},
        {"ARGUMENT_ERROR", "Erro de análise de argumentos"},
        {"INVALID_OUTPUT_DIR", "Diretório de saída inválido"},
        {"HIGH_CUT_RATIO_WARNING", "Aviso: Proporção máxima de corte é muito alta"},
        {"SUCCESSFULLY_TRIMMED", "Cortado com sucesso"},
        {"NO_CHANGES", "Nenhuma alteração feita"},
        {"SUPPORTED_FORMATS", "Formatos suportados"},
        {"SAFETY_NOTES", "Notas de segurança"}
    };

    // =========================
    // Spanish
    // =========================
    translations[Language::ES] = {
        {"START_MSG", "RomTrimmer++ iniciado"},
        {"SIMULATION_MODE", "MODO SIMULACIÓN - No se modificarán archivos"},
        {"ANALYSIS_MODE", "MODO ANÁLISIS - Solo se generarán informes"},
        {"PROCESSING", "Procesando: "},
        {"UNKNOWN_ROM", "Tipo de ROM desconocido, omitiendo..."},
        {"NO_PADDING", "No se encontró padding"},
        {"TRIM_SUCCESS", "Recorte exitoso: "},
        {"SAVED_SPACE", "Espacio recuperado: "},
        {"EXEC_SUMMARY", "=== RESUMEN DE EJECUCIÓN ==="},
        {"NO_INPUT", "Error: No se especificó ningún archivo o directorio"},
        {"USAGE", "Uso:"},
        {"EXAMPLES", "Ejemplos:"},
        {"OPTIONS", "Opciones:"},
        {"INPUT_HELP", "Archivo(s) de entrada a procesar"},
        {"PATH_HELP", "Directorio que contiene ROMs"},
        {"RECURSIVE_HELP", "Buscar en subdirectorios recursivamente"},
        {"OUTPUT_HELP", "Directorio de salida para ROMs recortadas"},
        {"HELP_HELP", "Mostrar este mensaje de ayuda"},
        {"VERSION_HELP", "Mostrar información de versión"},
        {"VERBOSE_HELP", "Salida detallada"},
        {"TRY_HELP", "Pruebe 'romtrimmer++ --help' para más información."},
        {"CRITICAL_ERROR", "Error crítico: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "Un potente utilitario de recorte de ROMs"},
        {"FILES_PROCESSED", "Archivos procesados"},
        {"FILES_TRIMMED", "Archivos recortados"},
        {"FILES_FAILED", "Archivos fallados"},
        {"SPACE_RECOVERED", "Espacio recuperado"},
        {"DETAILS_TITLE", "=== DETALLES POR ARCHIVO ==="},
        {"ORIGINAL_SIZE", "Original"},
        {"FINAL_SIZE", "Final"},
        {"REDUCTION", "Reducción"},
        {"ERROR_LABEL", "ERROR"},
        {"EMPTY_FILE", "Archivo vacío o no se pudo leer"},
        {"AUTO_PADDING_DETECTED", "Padding auto-detectado: 0x"},
        {"UNSAFE_TRIM", "Recorte no seguro: "},
        {"WARNING_FORCING_TRIM", "ADVERTENCIA: Forzando recorte - "},
        {"ANALYSIS", "Análisis: "},
        {"CAN_BE_REMOVED", " pueden ser removidos ("},
        {"SIMULATION_REMOVE", "Simulación: Removería "},
        {"WRITE_FILE_ERROR", "Fallo al escribir archivo"},
        {"ERROR_PROCESSING", "Error procesando "},
        {"CANNOT_CREATE_OUTPUT", "No se pudo crear archivo de salida"},
        {"ERROR_WRITING", "Error escribiendo: "},
        {"CANNOT_OPEN_FILE", "No se pudo abrir archivo"},
        {"ERROR_READING_FILE", "Error leyendo archivo"},
        {"PATH_NOT_EXIST", "La ruta no existe: "},
        {"FILES_FOUND", " archivo(s) encontrado(s)"},
        {"BACKUP_EXISTS_OVERWRITING", "La copia de seguridad ya existe, sobrescribiendo: "},
        {"BACKUP_CREATED", "Copia de seguridad creada: "},
        {"BACKUP_FAILED", "Fallo al crear copia de seguridad: "},
        {"FINAL_SIZE_BELOW_MIN", "Tamaño final ("},
        {"BELOW_MINIMUM_ALLOWED", ") por debajo del mínimo permitido ("},
        {"CUT_TOO_AGGRESSIVE", "Corte demasiado agresivo ("},
        {"EXCEEDS_LIMIT", "%) excede el límite ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "Archivo demasiado pequeño tras el corte ("},
        {"BELOW_SAFETY_MARGIN", " bytes), por debajo del margen de seguridad"},
        {"GBA_VALIDATION_FAILED", "Validación GBA fallida - posibles datos importantes tras el punto de corte"},
        {"NDS_VALIDATION_FAILED", "Validación NDS fallida - offsets ARM9/ARM7 pueden ser inválidos"},
        {"GB_VALIDATION_FAILED", "Validación GB/GBC fallida - la estructura de la ROM puede estar comprometida"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "Corte demasiado grande para tipo de ROM desconocido"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "El corte interrumpiría estructuras conocidas de la ROM"},
        {"FORCE_HELP", "Forzar operaciones inseguras"},
        {"EXAMPLE_TRIM_SINGLE", "Recortar archivo único: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "Procesar directorio: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "Solo analizar: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "OK"},
        {"HIGH_RISK_OPERATION", "Operación de alto riesgo: "},
        {"VALIDATION_EXCEPTION", "Excepción de validación: "},
        {"EMPTY_DATA", "Datos vacíos proporcionados"},
        {"LARGE_CUT_WARNING", "Corte grande detectado ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "Considere usar --analyze primero o --force si está seguro"},
        {"HEADER_INTEGRITY_COMPROMISED", "La integridad del encabezado de la ROM estaría comprometida"},
        {"SUGGEST_BACKUP_AND_VERIFY", "Cree copia de seguridad y verifique la funcionalidad de la ROM después del recorte"},
        {"RISK_LARGE_CUT", "Corte grande ("},
        {"RISK_BELOW_RECOMMENDED", "Tamaño por debajo del mínimo recomendado"},
        {"RISK_STRUCTURE_CONFLICT", "El corte afectaría estructuras de datos conocidas"},
        {"RECOMMENDATION_LOW_RISK", "Operación de bajo riesgo, proceda normalmente"},
        {"RECOMMENDATION_MEDIUM_RISK", "Riesgo medio, considere usar --analyze primero"},
        {"RECOMMENDATION_HIGH_RISK", "Alto riesgo, use --force solo si está absolutamente seguro"},
        {"RECOMMENDATION_CRITICAL_RISK", "Riesgo crítico, operación no recomendada"},
        {"INTERRUPT_RECEIVED", "Operación interrumpida por el usuario"},
        {"SEGMENTATION_FAULT", "Fallo de segmentación detectado"},
        {"PLEASE_REPORT_BUG", "Por favor, informe este problema en el repositorio del proyecto"},
        {"TERMINATION_REQUESTED", "Terminación solicitada, limpiando..."},
        {"LANGUAGE_SET", "Idioma establecido a"},
        {"LANGUAGE_ERROR", "Error de configuración de idioma"},
        {"FALLBACK_TO_ENGLISH", "Volviendo al Inglés"},
        {"QUICK_EXAMPLES", "Ejemplos rápidos"},
        {"TROUBLESHOOTING_TIPS", "Consejos para solución de problemas"},
        {"CHECK_PERMISSIONS", "Verifique permisos de archivo y directorio"},
        {"VERIFY_INPUT_FILES", "Verifique que los archivos de entrada sean ROMs válidas"},
        {"TRY_DRY_RUN_FIRST", "Intente con --dry-run primero para ver qué pasaría"},
        {"REPORT_ISSUE", "Informe este problema con detalles en el repositorio del proyecto"},
        {"NO_BACKUP_HELP", "No crear archivos de copia de seguridad"},
        {"ARGUMENT_ERROR", "Error de análisis de argumentos"},
        {"INVALID_OUTPUT_DIR", "Directorio de salida inválido"},
        {"HIGH_CUT_RATIO_WARNING", "Advertencia: La proporción máxima de corte es muy alta"},
        {"SUCCESSFULLY_TRIMMED", "Recortado exitosamente"},
        {"NO_CHANGES", "No se realizaron cambios"},
        {"SUPPORTED_FORMATS", "Formatos soportados"},
        {"SAFETY_NOTES", "Notas de seguridad"}
    };

    // =========================
    // French
    // =========================
    translations[Language::FR] = {
        {"START_MSG", "RomTrimmer++ démarré"},
        {"SIMULATION_MODE", "MODE SIMULATION - Aucun fichier ne sera modifié"},
        {"ANALYSIS_MODE", "MODE ANALYSE - Seuls les rapports seront générés"},
        {"PROCESSING", "Traitement: "},
        {"UNKNOWN_ROM", "Type de ROM inconnu, ignoré..."},
        {"NO_PADDING", "Aucun remplissage trouvé"},
        {"TRIM_SUCCESS", "Découpage réussi: "},
        {"SAVED_SPACE", "Espace récupéré: "},
        {"EXEC_SUMMARY", "=== RÉSUMÉ DE L'EXÉCUTION ==="},
        {"NO_INPUT", "Erreur: Aucun fichier ou dossier spécifié"},
        {"USAGE", "Utilisation:"},
        {"EXAMPLES", "Exemples:"},
        {"OPTIONS", "Options:"},
        {"INPUT_HELP", "Fichier(s) à traiter"},
        {"PATH_HELP", "Dossier contenant les ROMs"},
        {"RECURSIVE_HELP", "Recherche récursive"},
        {"OUTPUT_HELP", "Dossier de sortie"},
        {"HELP_HELP", "Afficher l'aide"},
        {"VERSION_HELP", "Afficher la version"},
        {"VERBOSE_HELP", "Sortie détaillée"},
        {"TRY_HELP", "Essayez 'romtrimmer++ --help' pour plus d'informations."},
        {"CRITICAL_ERROR", "Erreur critique: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "Un puissant outil de découpe de ROMs"},
        {"FILES_PROCESSED", "Fichiers traités"},
        {"FILES_TRIMMED", "Fichiers découpés"},
        {"FILES_FAILED", "Fichiers échoués"},
        {"SPACE_RECOVERED", "Espace récupéré"},
        {"DETAILS_TITLE", "=== DÉTAILS PAR FICHIER ==="},
        {"ORIGINAL_SIZE", "Original"},
        {"FINAL_SIZE", "Final"},
        {"REDUCTION", "Réduction"},
        {"ERROR_LABEL", "ERREUR"},
        {"EMPTY_FILE", "Fichier vide ou impossible à lire"},
        {"AUTO_PADDING_DETECTED", "Remplissage auto-détecté: 0x"},
        {"UNSAFE_TRIM", "Découpage non sécurisé: "},
        {"WARNING_FORCING_TRIM", "ATTENTION: Forçage du découpage - "},
        {"ANALYSIS", "Analyse: "},
        {"CAN_BE_REMOVED", " peuvent être supprimés ("},
        {"SIMULATION_REMOVE", "Simulation: Supprimerait "},
        {"WRITE_FILE_ERROR", "Échec de l'écriture du fichier"},
        {"ERROR_PROCESSING", "Erreur de traitement "},
        {"CANNOT_CREATE_OUTPUT", "Impossible de créer le fichier de sortie"},
        {"ERROR_WRITING", "Erreur d'écriture: "},
        {"CANNOT_OPEN_FILE", "Impossible d'ouvrir le fichier"},
        {"ERROR_READING_FILE", "Erreur de lecture du fichier"},
        {"PATH_NOT_EXIST", "Le chemin n'existe pas: "},
        {"FILES_FOUND", " fichier(s) trouvé(s)"},
        {"BACKUP_EXISTS_OVERWRITING", "La sauvegarde existe déjà, écrasement: "},
        {"BACKUP_CREATED", "Sauvegarde créée: "},
        {"BACKUP_FAILED", "Échec de la création de la sauvegarde: "},
        {"FINAL_SIZE_BELOW_MIN", "Taille finale ("},
        {"BELOW_MINIMUM_ALLOWED", ") inférieure au minimum autorisé ("},
        {"CUT_TOO_AGGRESSIVE", "Coupe trop agressive ("},
        {"EXCEEDS_LIMIT", "%) dépasse la limite ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "Fichier trop petit après coupure ("},
        {"BELOW_SAFETY_MARGIN", " octets), en dessous de la marge de sécurité"},
        {"GBA_VALIDATION_FAILED", "Validation GBA échouée - données importantes possibles après le point de coupure"},
        {"NDS_VALIDATION_FAILED", "Validation NDS échouée - les décalages ARM9/ARM7 peuvent être invalides"},
        {"GB_VALIDATION_FAILED", "Validation GB/GBC échouée - la structure de la ROM peut être compromise"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "Coupe trop grande pour un type de ROM inconnu"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "La coupe interromprait des structures connues de la ROM"},
        {"FORCE_HELP", "Forcer les opérations non sécurisées"},
        {"EXAMPLE_TRIM_SINGLE", "Découper un seul fichier: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "Traiter un répertoire: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "Analyser seulement: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "OK"},
        {"HIGH_RISK_OPERATION", "Opération à haut risque: "},
        {"VALIDATION_EXCEPTION", "Exception de validation: "},
        {"EMPTY_DATA", "Données vides fournies"},
        {"LARGE_CUT_WARNING", "Grande coupe détectée ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "Envisagez d'utiliser --analyze d'abord ou --force si sûr"},
        {"HEADER_INTEGRITY_COMPROMISED", "L'intégrité de l'en-tête de la ROM serait compromise"},
        {"SUGGEST_BACKUP_AND_VERIFY", "Créez une sauvegarde et vérifiez la fonctionnalité de la ROM après la découpe"},
        {"RISK_LARGE_CUT", "Grande coupe ("},
        {"RISK_BELOW_RECOMMENDED", "Taille inférieure au minimum recommandé"},
        {"RISK_STRUCTURE_CONFLICT", "La coupe affecterait des structures de données connues"},
        {"RECOMMENDATION_LOW_RISK", "Opération à faible risque, procédez normalement"},
        {"RECOMMENDATION_MEDIUM_RISK", "Risque moyen, envisagez d'utiliser --analyze d'abord"},
        {"RECOMMENDATION_HIGH_RISK", "Risque élevé, utilisez --force seulement si vous êtes absolument certain"},
        {"RECOMMENDATION_CRITICAL_RISK", "Risque critique, opération non recommandée"},
        {"INTERRUPT_RECEIVED", "Opération interrompue par l'utilisateur"},
        {"SEGMENTATION_FAULT", "Erreur de segmentation détectée"},
        {"PLEASE_REPORT_BUG", "Veuillez signaler ce problème sur le dépôt du projet"},
        {"TERMINATION_REQUESTED", "Terminaison demandée, nettoyage en cours..."},
        {"LANGUAGE_SET", "Langue définie sur"},
        {"LANGUAGE_ERROR", "Erreur de configuration de langue"},
        {"FALLBACK_TO_ENGLISH", "Retour à l'Anglais"},
        {"QUICK_EXAMPLES", "Exemples rapides"},
        {"TROUBLESHOOTING_TIPS", "Conseils de dépannage"},
        {"CHECK_PERMISSIONS", "Vérifiez les autorisations de fichier et de répertoire"},
        {"VERIFY_INPUT_FILES", "Vérifiez que les fichiers d'entrée sont des ROMs valides"},
        {"TRY_DRY_RUN_FIRST", "Essayez d'abord avec --dry-run pour voir ce qui se passerait"},
        {"REPORT_ISSUE", "Signalez ce problème avec des détails sur le dépôt du projet"},
        {"NO_BACKUP_HELP", "Ne pas créer de fichiers de sauvegarde"},
        {"ARGUMENT_ERROR", "Erreur d'analyse d'argument"},
        {"INVALID_OUTPUT_DIR", "Répertoire de sortie invalide"},
        {"HIGH_CUT_RATIO_WARNING", "Avertissement: Le ratio de coupe maximum est très élevé"},
        {"SUCCESSFULLY_TRIMMED", "Découpé avec succès"},
        {"NO_CHANGES", "Aucun changement effectué"},
        {"SUPPORTED_FORMATS", "Formats pris en charge"},
        {"SAFETY_NOTES", "Notes de sécurité"}
    };

    // =========================
    // Arabic
    // =========================
    translations[Language::AR] = {
        {"START_MSG", "بدأ RomTrimmer++"},
        {"SIMULATION_MODE", "وضع المحاكاة - لن يتم تغيير أي ملفات"},
        {"ANALYSIS_MODE", "وضع التحليل - سيتم إنشاء التقارير فقط"},
        {"PROCESSING", "جارٍ المعالجة: "},
        {"UNKNOWN_ROM", "نوع ROM غير معروف، يتم التخطي..."},
        {"NO_PADDING", "لم يتم العثور على حشو"},
        {"TRIM_SUCCESS", "تم القص بنجاح: "},
        {"SAVED_SPACE", "المساحة المستردة: "},
        {"EXEC_SUMMARY", "=== ملخص التنفيذ ==="},
        {"NO_INPUT", "خطأ: لم يتم تحديد ملف أو مجلد"},
        {"USAGE", "طريقة الاستخدام:"},
        {"EXAMPLES", "أمثلة:"},
        {"OPTIONS", "خيارات:"},
        {"INPUT_HELP", "ملف الإدخال"},
        {"PATH_HELP", "مجلد ROMs"},
        {"RECURSIVE_HELP", "بحث متكرر"},
        {"OUTPUT_HELP", "مجلد الإخراج"},
        {"HELP_HELP", "عرض المساعدة"},
        {"VERSION_HELP", "عرض الإصدار"},
        {"VERBOSE_HELP", "إخراج مفصل"},
        {"TRY_HELP", "جرب 'romtrimmer++ --help' لمزيد من المعلومات."},
        {"CRITICAL_ERROR", "خطأ حرج: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "أداة قوية لتشذيب ROMs"},
        {"FILES_PROCESSED", "الملفات المعالجة"},
        {"FILES_TRIMMED", "الملفات المشذبة"},
        {"FILES_FAILED", "الملفات الفاشلة"},
        {"SPACE_RECOVERED", "المساحة المستردة"},
        {"DETAILS_TITLE", "=== تفاصيل الملف ==="},
        {"ORIGINAL_SIZE", "الأصلي"},
        {"FINAL_SIZE", "النهائي"},
        {"REDUCTION", "تخفيض"},
        {"ERROR_LABEL", "خطأ"},
        {"EMPTY_FILE", "ملف فارغ أو لا يمكن قراءته"},
        {"AUTO_PADDING_DETECTED", "حشو مكتشف تلقائياً: 0x"},
        {"UNSAFE_TRIM", "قص غير آمن: "},
        {"WARNING_FORCING_TRIM", "تحذير: إجبار القص - "},
        {"ANALYSIS", "تحليل: "},
        {"CAN_BE_REMOVED", " يمكن إزالته ("},
        {"SIMULATION_REMOVE", "محاكاة: سيزيل "},
        {"WRITE_FILE_ERROR", "فشل في كتابة الملف"},
        {"ERROR_PROCESSING", "خطأ في معالجة "},
        {"CANNOT_CREATE_OUTPUT", "لا يمكن إنشاء ملف الإخراج"},
        {"ERROR_WRITING", "خطأ في الكتابة: "},
        {"CANNOT_OPEN_FILE", "لا يمكن فتح الملف"},
        {"ERROR_READING_FILE", "خطأ في قراءة الملف"},
        {"PATH_NOT_EXIST", "المسار غير موجود: "},
        {"FILES_FOUND", " ملف/ملفات تم العثور عليها"},
        {"BACKUP_EXISTS_OVERWRITING", "النسخة الاحتياطية موجودة بالفعل، سيتم الكتابة فوق: "},
        {"BACKUP_CREATED", "تم إنشاء نسخة احتياطية: "},
        {"BACKUP_FAILED", "فشل في إنشاء نسخة احتياطية: "},
        {"FINAL_SIZE_BELOW_MIN", "الحجم النهائي ("},
        {"BELOW_MINIMUM_ALLOWED", ") أقل من الحد الأدنى المسموح به ("},
        {"CUT_TOO_AGGRESSIVE", "القص عدواني جداً ("},
        {"EXCEEDS_LIMIT", "%) يتجاوز الحد ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "الملف صغير جداً بعد القص ("},
        {"BELOW_SAFETY_MARGIN", " بايت)، أقل من هامش الأمان"},
        {"GBA_VALIDATION_FAILED", "فشل التحقق من GBA - قد تكون هناك بيانات مهمة بعد نقطة القص"},
        {"NDS_VALIDATION_FAILED", "فشل التحقق من NDS - إزاحات ARM9/ARM7 قد تكون غير صالحة"},
        {"GB_VALIDATION_FAILED", "فشل التحقق من GB/GBC - بنية ROM قد تكون معرضة للخطر"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "قص كبير جداً لنوع ROM غير معروف"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "سيعطل القص الهياكل المعروفة لـ ROM"},
        {"FORCE_HELP", "فرض العمليات غير الآمنة"},
        {"EXAMPLE_TRIM_SINGLE", "قص ملف واحد: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "معالجة مجلد: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "تحليل فقط: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "موافق"},
        {"HIGH_RISK_OPERATION", "عملية عالية المخاطر: "},
        {"VALIDATION_EXCEPTION", "استثناء تحقق: "},
        {"EMPTY_DATA", "بيانات فارغة مقدمة"},
        {"LARGE_CUT_WARNING", "تم اكتشاف قطع كبير ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "فكر في استخدام --analyze أولاً أو --force إذا كنت متأكداً"},
        {"HEADER_INTEGRITY_COMPROMISED", "سلامة رأس ROM ستكون معرضة للخطر"},
        {"SUGGEST_BACKUP_AND_VERIFY", "أنشئ نسخة احتياطية وتحقق من وظيفة ROM بعد التشذيب"},
        {"RISK_LARGE_CUT", "قطع كبير ("},
        {"RISK_BELOW_RECOMMENDED", "الحجم أقل من الحد الأدنى الموصى به"},
        {"RISK_STRUCTURE_CONFLICT", "سيتأثر الهياكل المعروفة للبيانات"},
        {"RECOMMENDATION_LOW_RISK", "عملية منخفضة المخاطر، تابع بشكل طبيعي"},
        {"RECOMMENDATION_MEDIUM_RISK", "مخاطر متوسطة، فكر في استخدام --analyze أولاً"},
        {"RECOMMENDATION_HIGH_RISK", "مخاطر عالية، استخدم --force فقط إذا كنت متأكداً تماماً"},
        {"RECOMMENDATION_CRITICAL_RISK", "مخاطر حرجة، العملية غير موصى بها"},
        {"INTERRUPT_RECEIVED", "تمت مقاطعة العملية من قبل المستخدم"},
        {"SEGMENTATION_FAULT", "تم اكتشاف خطأ في التجزئة"},
        {"PLEASE_REPORT_BUG", "يرجى الإبلاغ عن هذه المشكلة في مستودع المشروع"},
        {"TERMINATION_REQUESTED", "تم طلب الإنهاء، جارٍ التنظيف..."},
        {"LANGUAGE_SET", "تم تعيين اللغة إلى"},
        {"LANGUAGE_ERROR", "خطأ في تكوين اللغة"},
        {"FALLBACK_TO_ENGLISH", "التراجع إلى اللغة الإنجليزية"},
        {"QUICK_EXAMPLES", "أمثلة سريعة"},
        {"TROUBLESHOOTING_TIPS", "نصائح استكشاف الأخطاء وإصلاحها"},
        {"CHECK_PERMISSIONS", "تحقق من أذونات الملف والمجلد"},
        {"VERIFY_INPUT_FILES", "تحقق من أن ملفات الإدخال هي ROMs صالحة"},
        {"TRY_DRY_RUN_FIRST", "جرب أولاً مع --dry-run لترى ما سيحدث"},
        {"REPORT_ISSUE", "أبلغ عن هذه المشكلة مع تفاصيل في مستودع المشروع"},
        {"NO_BACKUP_HELP", "لا تنشئ ملفات نسخ احتياطي"},
        {"ARGUMENT_ERROR", "خطأ في تحليل الوسائط"},
        {"INVALID_OUTPUT_DIR", "مجلد إخراج غير صالح"},
        {"HIGH_CUT_RATIO_WARNING", "تحذير: نسبة القص القصوى عالية جداً"},
        {"SUCCESSFULLY_TRIMMED", "تم القص بنجاح"},
        {"NO_CHANGES", "لم يتم إجراء أي تغييرات"},
        {"SUPPORTED_FORMATS", "التنسيقات المدعومة"},
        {"SAFETY_NOTES", "ملاحظات السلامة"}
    };

    // =========================
    // Hindi
    // =========================
    translations[Language::HI] = {
        {"START_MSG", "RomTrimmer++ शुरू हुआ"},
        {"SIMULATION_MODE", "सिमुलेशन मोड - कोई फ़ाइल नहीं बदली जाएगी"},
        {"ANALYSIS_MODE", "विश्लेषण मोड - केवल रिपोर्ट बनाई जाएँगी"},
        {"PROCESSING", "प्रसंस्करण: "},
        {"UNKNOWN_ROM", "अज्ञात ROM प्रकार, छोड़ा जा रहा है..."},
        {"NO_PADDING", "कोई पैडिंग नहीं मिली"},
        {"TRIM_SUCCESS", "सफलतापूर्वक ट्रिम किया गया: "},
        {"SAVED_SPACE", "रिकवर की गई जगह: "},
        {"EXEC_SUMMARY", "=== निष्पादन सारांश ==="},
        {"NO_INPUT", "त्रुटि: कोई इनपुट फ़ाइल या फ़ोल्डर निर्दिष्ट नहीं"},
        {"USAGE", "उपयोग:"},
        {"EXAMPLES", "उदाहरण:"},
        {"OPTIONS", "विकल्प:"},
        {"INPUT_HELP", "इनपुट फ़ाइल"},
        {"PATH_HELP", "ROMs वाला फ़ोल्डर"},
        {"RECURSIVE_HELP", "रिकर्सिव खोज"},
        {"OUTPUT_HELP", "आउटपुट फ़ोल्डर"},
        {"HELP_HELP", "मदद दिखाएँ"},
        {"VERSION_HELP", "संस्करण जानकारी"},
        {"VERBOSE_HELP", "विस्तृत आउटपुट"},
        {"TRY_HELP", "'romtrimmer++ --help' आज़माएँ"},
        {"CRITICAL_ERROR", "गंभीर त्रुटि: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "एक शक्तिशाली ROM ट्रिमिंग टूल"},
        {"FILES_PROCESSED", "फ़ाइलें संसाधित"},
        {"FILES_TRIMMED", "फ़ाइलें ट्रिम की गई"},
        {"FILES_FAILED", "फ़ाइलें विफल"},
        {"SPACE_RECOVERED", "पुनः प्राप्त स्थान"},
        {"DETAILS_TITLE", "=== फ़ाइल विवरण ==="},
        {"ORIGINAL_SIZE", "मूल"},
        {"FINAL_SIZE", "अंतिम"},
        {"REDUCTION", "कटौती"},
        {"ERROR_LABEL", "त्रुटि"},
        {"EMPTY_FILE", "खाली फ़ाइल या पढ़ी नहीं जा सकी"},
        {"AUTO_PADDING_DETECTED", "स्वतः पता चला पैडिंग: 0x"},
        {"UNSAFE_TRIM", "असुरक्षित ट्रिम: "},
        {"WARNING_FORCING_TRIM", "चेतावनी: ट्रिम बलपूर्वक कर रहा है - "},
        {"ANALYSIS", "विश्लेषण: "},
        {"CAN_BE_REMOVED", " हटाए जा सकते हैं ("},
        {"SIMULATION_REMOVE", "सिमुलेशन: हटाएगा "},
        {"WRITE_FILE_ERROR", "फ़ाइल लिखने में विफल"},
        {"ERROR_PROCESSING", "प्रसंस्करण में त्रुटि "},
        {"CANNOT_CREATE_OUTPUT", "आउटपुट फ़ाइल नहीं बना सकता"},
        {"ERROR_WRITING", "लिखने में त्रुटि: "},
        {"CANNOT_OPEN_FILE", "फ़ाइल नहीं खोल सकता"},
        {"ERROR_READING_FILE", "फ़ाइल पढ़ने में त्रुटि"},
        {"PATH_NOT_EXIST", "पथ मौजूद नहीं है: "},
        {"FILES_FOUND", " फ़ाइल(एँ) मिली"},
        {"BACKUP_EXISTS_OVERWRITING", "बैकअप पहले से मौजूद है, ओवरराइट कर रहा है: "},
        {"BACKUP_CREATED", "बैकअप बनाया गया: "},
        {"BACKUP_FAILED", "बैकअप बनाने में विफल: "},
        {"FINAL_SIZE_BELOW_MIN", "अंतिम आकार ("},
        {"BELOW_MINIMUM_ALLOWED", ") न्यूनतम अनुमत से कम ("},
        {"CUT_TOO_AGGRESSIVE", "कटाव बहुत आक्रामक ("},
        {"EXCEEDS_LIMIT", "%) सीमा से अधिक ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "कटाव के बाद फ़ाइल बहुत छोटी ("},
        {"BELOW_SAFETY_MARGIN", " बाइट), सुरक्षा मार्जिन से नीचे"},
        {"GBA_VALIDATION_FAILED", "GBA सत्यापन विफल - कटाव बिंदु के बाद महत्वपूर्ण डेटा संभव"},
        {"NDS_VALIDATION_FAILED", "NDS सत्यापन विफल - ARM9/ARM7 ऑफ़सेट अमान्य हो सकते हैं"},
        {"GB_VALIDATION_FAILED", "GB/GBC सत्यापन विफल - ROM संरचना समझौता हो सकती है"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "अज्ञात ROM प्रकार के लिए कटाव बहुत बड़ा"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "कटाव ज्ञात ROM संरचनाओं को बाधित करेगा"},
        {"FORCE_HELP", "असुरक्षित ऑपरेशन बलपूर्वक करें"},
        {"EXAMPLE_TRIM_SINGLE", "एकल फ़ाइल ट्रिम करें: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "डायरेक्टरी प्रोसेस करें: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "केवल विश्लेषण करें: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "ठीक"},
        {"HIGH_RISK_OPERATION", "उच्च जोखिम ऑपरेशन: "},
        {"VALIDATION_EXCEPTION", "सत्यापन अपवाद: "},
        {"EMPTY_DATA", "खाली डेटा प्रदान किया गया"},
        {"LARGE_CUT_WARNING", "बड़ा कटाव पाया गया ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "पहले --analyze या यदि निश्चित हैं तो --force का उपयोग करने पर विचार करें"},
        {"HEADER_INTEGRITY_COMPROMISED", "ROM हेडर अखंडता समझौता होगी"},
        {"SUGGEST_BACKUP_AND_VERIFY", "बैकअप बनाएँ और ट्रिम के बाद ROM कार्यक्षमता सत्यापित करें"},
        {"RISK_LARGE_CUT", "बड़ा कटाव ("},
        {"RISK_BELOW_RECOMMENDED", "आकार अनुशंसित न्यूनतम से नीचे"},
        {"RISK_STRUCTURE_CONFLICT", "कटाव ज्ञात डेटा संरचनाओं को प्रभावित करेगा"},
        {"RECOMMENDATION_LOW_RISK", "कम जोखिम ऑपरेशन, सामान्य रूप से आगे बढ़ें"},
        {"RECOMMENDATION_MEDIUM_RISK", "मध्यम जोखिम, पहले --analyze का उपयोग करने पर विचार करें"},
        {"RECOMMENDATION_HIGH_RISK", "उच्च जोखिम, केवल तभी --force का उपयोग करें जब बिल्कुल निश्चित हों"},
        {"RECOMMENDATION_CRITICAL_RISK", "गंभीर जोखिम, ऑपरेशन अनुशंसित नहीं"},
        {"INTERRUPT_RECEIVED", "ऑपरेशन उपयोगकर्ता द्वारा बाधित"},
        {"SEGMENTATION_FAULT", "सेगमेंटेशन फॉल्ट पाया गया"},
        {"PLEASE_REPORT_BUG", "कृपया इस समस्या को प्रोजेक्ट रिपॉजिटरी पर रिपोर्ट करें"},
        {"TERMINATION_REQUESTED", "समाप्ति अनुरोधित, सफाई हो रही है..."},
        {"LANGUAGE_SET", "भाषा सेट की गई"},
        {"LANGUAGE_ERROR", "भाषा कॉन्फ़िगरेशन त्रुटि"},
        {"FALLBACK_TO_ENGLISH", "अंग्रेजी पर वापस आ रहे हैं"},
        {"QUICK_EXAMPLES", "त्वरित उदाहरण"},
        {"TROUBLESHOOTING_TIPS", "समस्या निवारण युक्तियाँ"},
        {"CHECK_PERMISSIONS", "फ़ाइल और डायरेक्टरी अनुमतियाँ जाँचें"},
        {"VERIFY_INPUT_FILES", "सत्यापित करें कि इनपुट फ़ाइलें मान्य ROMs हैं"},
        {"TRY_DRY_RUN_FIRST", "पहले --dry-run के साथ आज़माएँ कि क्या होगा"},
        {"REPORT_ISSUE", "प्रोजेक्ट रिपॉजिटरी पर विवरण के साथ इस समस्या को रिपोर्ट करें"},
        {"NO_BACKUP_HELP", "बैकअप फ़ाइलें न बनाएँ"},
        {"ARGUMENT_ERROR", "तर्क पार्सिंग त्रुटि"},
        {"INVALID_OUTPUT_DIR", "अमान्य आउटपुट डायरेक्टरी"},
        {"HIGH_CUT_RATIO_WARNING", "चेतावनी: अधिकतम कटाव अनुपात बहुत अधिक है"},
        {"SUCCESSFULLY_TRIMMED", "सफलतापूर्वक ट्रिम किया गया"},
        {"NO_CHANGES", "कोई परिवर्तन नहीं किया गया"},
        {"SUPPORTED_FORMATS", "समर्थित स्वरूप"},
        {"SAFETY_NOTES", "सुरक्षा नोट्स"}
    };

    // =========================
    // Bengali
    // =========================
    translations[Language::BN] = {
        {"START_MSG", "RomTrimmer++ শুরু হয়েছে"},
        {"SIMULATION_MODE", "সিমুলেশন মোড - কোনো ফাইল পরিবর্তন হবে না"},
        {"ANALYSIS_MODE", "বিশ্লেষণ মোড - শুধুমাত্র রিপোর্ট তৈরি হবে"},
        {"PROCESSING", "প্রক্রিয়াকরণ: "},
        {"UNKNOWN_ROM", "অজানা ROM টাইপ, বাদ দেওয়া হচ্ছে..."},
        {"NO_PADDING", "কোনো প্যাডিং পাওয়া যায়নি"},
        {"TRIM_SUCCESS", "সফলভাবে ট্রিম হয়েছে: "},
        {"SAVED_SPACE", "উদ্ধারকৃত স্থান: "},
        {"EXEC_SUMMARY", "=== কার্যনির্বাহী সারাংশ ==="},
        {"NO_INPUT", "ত্রুটি: কোনো ইনপুট নির্দিষ্ট করা হয়নি"},
        {"USAGE", "ব্যবহার:"},
        {"EXAMPLES", "উদাহরণ:"},
        {"OPTIONS", "অপশন:"},
        {"INPUT_HELP", "ইনপুট ফাইল"},
        {"PATH_HELP", "ROMs ডিরেক্টরি"},
        {"RECURSIVE_HELP", "রিকার্সিভ অনুসন্ধান"},
        {"OUTPUT_HELP", "আউটপুট ডিরেক্টরি"},
        {"HELP_HELP", "সহায়তা দেখান"},
        {"VERSION_HELP", "ভার্সন তথ্য"},
        {"VERBOSE_HELP", "বিস্তারিত আউটপুট"},
        {"TRY_HELP", "'romtrimmer++ --help' চেষ্টা করুন"},
        {"CRITICAL_ERROR", "গুরুতর ত্রুটি: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "একটি শক্তিশালী ROM ট্রিমিং টুল"},
        {"FILES_PROCESSED", "ফাইল প্রক্রিয়াকৃত"},
        {"FILES_TRIMMED", "ফাইল ছাঁটা হয়েছে"},
        {"FILES_FAILED", "ফাইল ব্যর্থ"},
        {"SPACE_RECOVERED", "পুনরুদ্ধার করা স্থান"},
        {"DETAILS_TITLE", "=== ফাইল বিবরণ ==="},
        {"ORIGINAL_SIZE", "মূল"},
        {"FINAL_SIZE", "চূড়ান্ত"},
        {"REDUCTION", "হ্রাস"},
        {"ERROR_LABEL", "ত্রুটি"},
        {"EMPTY_FILE", "খালি ফাইল বা পড়া যায়নি"},
        {"AUTO_PADDING_DETECTED", "স্বয়ংক্রিয়ভাবে সনাক্ত প্যাডিং: 0x"},
        {"UNSAFE_TRIM", "অনিরাপদ ট্রিম: "},
        {"WARNING_FORCING_TRIM", "সতর্কতা: জোরপূর্বক ট্রিম করছে - "},
        {"ANALYSIS", "বিশ্লেষণ: "},
        {"CAN_BE_REMOVED", " সরানো যেতে পারে ("},
        {"SIMULATION_REMOVE", "সিমুলেশন: সরাবে "},
        {"WRITE_FILE_ERROR", "ফাইল লেখা ব্যর্থ"},
        {"ERROR_PROCESSING", "প্রক্রিয়াকরণে ত্রুটি "},
        {"CANNOT_CREATE_OUTPUT", "আউটপুট ফাইল তৈরি করতে পারে না"},
        {"ERROR_WRITING", "লেখায় ত্রুটি: "},
        {"CANNOT_OPEN_FILE", "ফাইল খুলতে পারে না"},
        {"ERROR_READING_FILE", "ফাইল পড়তে ত্রুটি"},
        {"PATH_NOT_EXIST", "পথ বিদ্যমান নেই: "},
        {"FILES_FOUND", " ফাইল পাওয়া গেছে"},
        {"BACKUP_EXISTS_OVERWRITING", "ব্যাকআপ ইতিমধ্যেই আছে, ওভাররাইট করছে: "},
        {"BACKUP_CREATED", "ব্যাকআপ তৈরি করা হয়েছে: "},
        {"BACKUP_FAILED", "ব্যাকআপ তৈরি করতে ব্যর্থ: "},
        {"FINAL_SIZE_BELOW_MIN", "চূড়ান্ত আকার ("},
        {"BELOW_MINIMUM_ALLOWED", ") সর্বনিম্ন অনুমোদিত এর নিচে ("},
        {"CUT_TOO_AGGRESSIVE", "কাটা খুব আক্রমণাত্মক ("},
        {"EXCEEDS_LIMIT", "%) সীমা অতিক্রম করেছে ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "কাটার পরে ফাইল খুব ছোট ("},
        {"BELOW_SAFETY_MARGIN", " বাইট), নিরাপত্তা মার্জিনের নিচে"},
        {"GBA_VALIDATION_FAILED", "GBA ভ্যালিডেশন ব্যর্থ - কাটার বিন্দুর পরে গুরুত্বপূর্ণ ডেটা সম্ভব"},
        {"NDS_VALIDATION_FAILED", "NDS ভ্যালিডেশন ব্যর্থ - ARM9/ARM7 অফসেট অবৈধ হতে পারে"},
        {"GB_VALIDATION_FAILED", "GB/GBC ভ্যালিডেশন ব্যর্থ - ROM কাঠামো ক্ষতিগ্রস্ত হতে পারে"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "অজানা ROM প্রকারের জন্য কাটা খুব বড়"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "কাটা পরিচিত ROM কাঠামোকে ব্যাহত করবে"},
        {"FORCE_HELP", "অনিরাপদ অপারেশন জোর করুন"},
        {"EXAMPLE_TRIM_SINGLE", "একক ফাইল ট্রিম করুন: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "ডিরেক্টরি প্রক্রিয়া করুন: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "শুধুমাত্র বিশ্লেষণ করুন: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "ঠিক আছে"},
        {"HIGH_RISK_OPERATION", "উচ্চ ঝুঁকির অপারেশন: "},
        {"VALIDATION_EXCEPTION", "ভ্যালিডেশন ব্যতিক্রম: "},
        {"EMPTY_DATA", "খালি ডেটা প্রদান করা হয়েছে"},
        {"LARGE_CUT_WARNING", "বড় কাটা সনাক্ত হয়েছে ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "প্রথমে --analyze ব্যবহার করুন বা নিশ্চিত হলে --force ব্যবহার করুন"},
        {"HEADER_INTEGRITY_COMPROMISED", "ROM হেডার অখণ্ডতা ক্ষতিগ্রস্ত হবে"},
        {"SUGGEST_BACKUP_AND_VERIFY", "ব্যাকআপ তৈরি করুন এবং ট্রিম করার পরে ROM কার্যকারিতা যাচাই করুন"},
        {"RISK_LARGE_CUT", "বড় কাটা ("},
        {"RISK_BELOW_RECOMMENDED", "আকার সুপারিশকৃত ন্যূনতমের নিচে"},
        {"RISK_STRUCTURE_CONFLICT", "কাটা পরিচিত ডেটা কাঠামোকে প্রভাবিত করবে"},
        {"RECOMMENDATION_LOW_RISK", "কম ঝুঁকির অপারেশন, স্বাভাবিকভাবে এগিয়ে যান"},
        {"RECOMMENDATION_MEDIUM_RISK", "মধ্যম ঝুঁকি, প্রথমে --analyze ব্যবহার করুন"},
        {"RECOMMENDATION_HIGH_RISK", "উচ্চ ঝুঁকি, শুধুমাত্র একেবারে নিশ্চিত হলে --force ব্যবহার করুন"},
        {"RECOMMENDATION_CRITICAL_RISK", "সমালোচনামূলক ঝুঁকি, অপারেশন সুপারিশ করা হয় না"},
        {"INTERRUPT_RECEIVED", "অপারেশন ব্যবহারকারী দ্বারা বাধাপ্রাপ্ত"},
        {"SEGMENTATION_FAULT", "সেগমেন্টেশন ফল্ট সনাক্ত করা হয়েছে"},
        {"PLEASE_REPORT_BUG", "দয়া করে এই সমস্যাটি প্রকৃতি রিপোজিটরিতে রিপোর্ট করুন"},
        {"TERMINATION_REQUESTED", "সমাপ্তি অনুরোধ করা হয়েছে, পরিষ্কার করা হচ্ছে..."},
        {"LANGUAGE_SET", "ভাষা সেট করা হয়েছে"},
        {"LANGUAGE_ERROR", "ভাষা কনফিগারেশন ত্রুটি"},
        {"FALLBACK_TO_ENGLISH", "ইংরেজিতে ফিরে যাচ্ছে"},
        {"QUICK_EXAMPLES", "দ্রুত উদাহরণ"},
        {"TROUBLESHOOTING_TIPS", "সমস্যা সমাধানের টিপস"},
        {"CHECK_PERMISSIONS", "ফাইল এবং ডিরেক্টরি অনুমতি চেক করুন"},
        {"VERIFY_INPUT_FILES", "যাচাই করুন যে ইনপুট ফাইলগুলি বৈধ ROMs"},
        {"TRY_DRY_RUN_FIRST", "প্রথমে --dry-run দিয়ে চেষ্টা করুন কী হবে"},
        {"REPORT_ISSUE", "প্রকল্প রিপোজিটরিতে বিস্তারিত সহ এই সমস্যাটি রিপোর্ট করুন"},
        {"NO_BACKUP_HELP", "ব্যাকআপ ফাইল তৈরি করবেন না"},
        {"ARGUMENT_ERROR", "যুক্তি পার্সিং ত্রুটি"},
        {"INVALID_OUTPUT_DIR", "অবৈধ আউটপুট ডিরেক্টরি"},
        {"HIGH_CUT_RATIO_WARNING", "সতর্কতা: সর্বোচ্চ কাটা অনুপাত খুব বেশি"},
        {"SUCCESSFULLY_TRIMMED", "সফলভাবে ছাঁটা হয়েছে"},
        {"NO_CHANGES", "কোনো পরিবর্তন করা হয়নি"},
        {"SUPPORTED_FORMATS", "সমর্থিত ফরম্যাট"},
        {"SAFETY_NOTES", "নিরাপত্তা নোট"}
    };

    // =========================
    // Russian
    // =========================
    translations[Language::RU] = {
        {"START_MSG", "RomTrimmer++ запущен"},
        {"SIMULATION_MODE", "РЕЖИМ СИМУЛЯЦИИ - файлы не будут изменены"},
        {"ANALYSIS_MODE", "РЕЖИМ АНАЛИЗА - будут созданы только отчёты"},
        {"PROCESSING", "Обработка: "},
        {"UNKNOWN_ROM", "Неизвестный тип ROM, пропуск..."},
        {"NO_PADDING", "Padding не найден"},
        {"TRIM_SUCCESS", "Обрезка выполнена: "},
        {"SAVED_SPACE", "Освобождено места: "},
        {"EXEC_SUMMARY", "=== СВОДКА ВЫПОЛНЕНИЯ ==="},
        {"NO_INPUT", "Ошибка: входной файл или каталог не указан"},
        {"USAGE", "Использование:"},
        {"EXAMPLES", "Примеры:"},
        {"OPTIONS", "Параметры:"},
        {"INPUT_HELP", "Входной файл"},
        {"PATH_HELP", "Каталог ROMs"},
        {"RECURSIVE_HELP", "Рекурсивный поиск"},
        {"OUTPUT_HELP", "Каталог вывода"},
        {"HELP_HELP", "Показать справку"},
        {"VERSION_HELP", "Информация о версии"},
        {"VERBOSE_HELP", "Подробный вывод"},
        {"TRY_HELP", "Попробуйте 'romtrimmer++ --help'"},
        {"CRITICAL_ERROR", "Критическая ошибка: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "Мощная утилита для обрезки ROM"},
        {"FILES_PROCESSED", "Файлов обработано"},
        {"FILES_TRIMMED", "Файлов обрезано"},
        {"FILES_FAILED", "Файлов с ошибками"},
        {"SPACE_RECOVERED", "Восстановлено места"},
        {"DETAILS_TITLE", "=== ДЕТАЛИ ФАЙЛА ==="},
        {"ORIGINAL_SIZE", "Исходный"},
        {"FINAL_SIZE", "Финальный"},
        {"REDUCTION", "Сокращение"},
        {"ERROR_LABEL", "ОШИБКА"},
        {"EMPTY_FILE", "Пустой файл или не удалось прочитать"},
        {"AUTO_PADDING_DETECTED", "Автоопределённый padding: 0x"},
        {"UNSAFE_TRIM", "Небезопасная обрезка: "},
        {"WARNING_FORCING_TRIM", "ПРЕДУПРЕЖДЕНИЕ: Принудительная обрезка - "},
        {"ANALYSIS", "Анализ: "},
        {"CAN_BE_REMOVED", " могут быть удалены ("},
        {"SIMULATION_REMOVE", "Симуляция: Удалит "},
        {"WRITE_FILE_ERROR", "Не удалось записать файл"},
        {"ERROR_PROCESSING", "Ошибка обработки "},
        {"CANNOT_CREATE_OUTPUT", "Не удалось создать выходной файл"},
        {"ERROR_WRITING", "Ошибка записи: "},
        {"CANNOT_OPEN_FILE", "Не удалось открыть файл"},
        {"ERROR_READING_FILE", "Ошибка чтения файла"},
        {"PATH_NOT_EXIST", "Путь не существует: "},
        {"FILES_FOUND", " файл(ов) найдено"},
        {"BACKUP_EXISTS_OVERWRITING", "Резервная копия уже существует, перезапись: "},
        {"BACKUP_CREATED", "Резервная копия создана: "},
        {"BACKUP_FAILED", "Не удалось создать резервную копию: "},
        {"FINAL_SIZE_BELOW_MIN", "Финальный размер ("},
        {"BELOW_MINIMUM_ALLOWED", ") ниже минимально допустимого ("},
        {"CUT_TOO_AGGRESSIVE", "Слишком агрессивное обрезание ("},
        {"EXCEEDS_LIMIT", "%) превышает лимит ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "Файл слишком мал после обрезки ("},
        {"BELOW_SAFETY_MARGIN", " байт), ниже запаса безопасности"},
        {"GBA_VALIDATION_FAILED", "Ошибка проверки GBA - возможны важные данные после точки обрезки"},
        {"NDS_VALIDATION_FAILED", "Ошибка проверки NDS - смещения ARM9/ARM7 могут быть недействительны"},
        {"GB_VALIDATION_FAILED", "Ошибка проверки GB/GBC - структура ROM может быть нарушена"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "Обрезка слишком велика для неизвестного типа ROM"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "Обрезка прервёт известные структуры ROM"},
        {"FORCE_HELP", "Принудительно выполнять небезопасные операции"},
        {"EXAMPLE_TRIM_SINGLE", "Обрезать один файл: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "Обработать каталог: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "Только анализ: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "ОК"},
        {"HIGH_RISK_OPERATION", "Операция высокого риска: "},
        {"VALIDATION_EXCEPTION", "Исключение проверки: "},
        {"EMPTY_DATA", "Предоставлены пустые данные"},
        {"LARGE_CUT_WARNING", "Обнаружена большая обрезка ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "Рассмотрите сначала использование --analyze или --force, если уверены"},
        {"HEADER_INTEGRITY_COMPROMISED", "Целостность заголовка ROM будет нарушена"},
        {"SUGGEST_BACKUP_AND_VERIFY", "Создайте резервную копию и проверьте функциональность ROM после обрезки"},
        {"RISK_LARGE_CUT", "Большая обрезка ("},
        {"RISK_BELOW_RECOMMENDED", "Размер ниже рекомендуемого минимума"},
        {"RISK_STRUCTURE_CONFLICT", "Обрезка повлияет на известные структуры данных"},
        {"RECOMMENDATION_LOW_RISK", "Операция низкого риска, продолжайте как обычно"},
        {"RECOMMENDATION_MEDIUM_RISK", "Средний риск, рассмотрите сначала использование --analyze"},
        {"RECOMMENDATION_HIGH_RISK", "Высокий риск, используйте --force только если абсолютно уверены"},
        {"RECOMMENDATION_CRITICAL_RISK", "Критический риск, операция не рекомендуется"},
        {"INTERRUPT_RECEIVED", "Операция прервана пользователем"},
        {"SEGMENTATION_FAULT", "Обнаружена ошибка сегментации"},
        {"PLEASE_REPORT_BUG", "Пожалуйста, сообщите об этой проблеме в репозитории проекта"},
        {"TERMINATION_REQUESTED", "Запрошено завершение, очистка..."},
        {"LANGUAGE_SET", "Язык установлен на"},
        {"LANGUAGE_ERROR", "Ошибка конфигурации языка"},
        {"FALLBACK_TO_ENGLISH", "Возврат к английскому"},
        {"QUICK_EXAMPLES", "Быстрые примеры"},
        {"TROUBLESHOOTING_TIPS", "Советы по устранению неполадок"},
        {"CHECK_PERMISSIONS", "Проверьте разрешения файлов и каталогов"},
        {"VERIFY_INPUT_FILES", "Убедитесь, что входные файлы являются валидными ROM"},
        {"TRY_DRY_RUN_FIRST", "Попробуйте сначала с --dry-run, чтобы увидеть, что произойдёт"},
        {"REPORT_ISSUE", "Сообщите об этой проблеме с подробностями в репозитории проекта"},
        {"NO_BACKUP_HELP", "Не создавать резервные копии файлов"},
        {"ARGUMENT_ERROR", "Ошибка разбора аргументов"},
        {"INVALID_OUTPUT_DIR", "Неверный выходной каталог"},
        {"HIGH_CUT_RATIO_WARNING", "Предупреждение: Максимальный коэффициент обрезки очень высок"},
        {"SUCCESSFULLY_TRIMMED", "Успешно обрезано"},
        {"NO_CHANGES", "Изменений не внесено"},
        {"SUPPORTED_FORMATS", "Поддерживаемые форматы"},
        {"SAFETY_NOTES", "Примечания по безопасности"}
    };

    // =========================
    // Chinese (Simplified)
    // =========================
    translations[Language::ZH] = {
        {"START_MSG", "RomTrimmer++ 已启动"},
        {"SIMULATION_MODE", "模拟模式 - 不会更改任何文件"},
        {"ANALYSIS_MODE", "分析模式 - 仅生成报告"},
        {"PROCESSING", "正在处理: "},
        {"UNKNOWN_ROM", "未知ROM类型，跳过..."},
        {"NO_PADDING", "未找到填充数据"},
        {"TRIM_SUCCESS", "修剪成功: "},
        {"SAVED_SPACE", "已恢复空间: "},
        {"EXEC_SUMMARY", "=== 执行摘要 ==="},
        {"NO_INPUT", "错误: 未指定输入文件或目录"},
        {"USAGE", "用法:"},
        {"EXAMPLES", "示例:"},
        {"OPTIONS", "选项:"},
        {"INPUT_HELP", "输入文件"},
        {"PATH_HELP", "包含ROM的目录"},
        {"RECURSIVE_HELP", "递归搜索"},
        {"OUTPUT_HELP", "输出目录"},
        {"HELP_HELP", "显示帮助"},
        {"VERSION_HELP", "版本信息"},
        {"VERBOSE_HELP", "详细输出"},
        {"TRY_HELP", "尝试 'romtrimmer++ --help' 获取更多信息"},
        {"CRITICAL_ERROR", "严重错误: "},
        {"A_POWERFUL_ROM_TRIMMING_UTILITY", "强大的ROM修剪工具"},
        {"FILES_PROCESSED", "文件已处理"},
        {"FILES_TRIMMED", "文件已修剪"},
        {"FILES_FAILED", "文件失败"},
        {"SPACE_RECOVERED", "已恢复空间"},
        {"DETAILS_TITLE", "=== 文件详情 ==="},
        {"ORIGINAL_SIZE", "原始"},
        {"FINAL_SIZE", "最终"},
        {"REDUCTION", "减少"},
        {"ERROR_LABEL", "错误"},
        {"EMPTY_FILE", "空文件或无法读取"},
        {"AUTO_PADDING_DETECTED", "自动检测到的填充: 0x"},
        {"UNSAFE_TRIM", "不安全修剪: "},
        {"WARNING_FORCING_TRIM", "警告: 强制修剪 - "},
        {"ANALYSIS", "分析: "},
        {"CAN_BE_REMOVED", " 可以被移除 ("},
        {"SIMULATION_REMOVE", "模拟: 将移除 "},
        {"WRITE_FILE_ERROR", "写入文件失败"},
        {"ERROR_PROCESSING", "处理错误 "},
        {"CANNOT_CREATE_OUTPUT", "无法创建输出文件"},
        {"ERROR_WRITING", "写入错误: "},
        {"CANNOT_OPEN_FILE", "无法打开文件"},
        {"ERROR_READING_FILE", "读取文件错误"},
        {"PATH_NOT_EXIST", "路径不存在: "},
        {"FILES_FOUND", " 个文件找到"},
        {"BACKUP_EXISTS_OVERWRITING", "备份已存在，正在覆盖: "},
        {"BACKUP_CREATED", "备份已创建: "},
        {"BACKUP_FAILED", "创建备份失败: "},
        {"FINAL_SIZE_BELOW_MIN", "最终大小 ("},
        {"BELOW_MINIMUM_ALLOWED", ") 低于允许的最小值 ("},
        {"CUT_TOO_AGGRESSIVE", "削减过于激进 ("},
        {"EXCEEDS_LIMIT", "%) 超过限制 ("},
        {"FILE_TOO_SMALL_AFTER_TRIM", "修剪后文件太小 ("},
        {"BELOW_SAFETY_MARGIN", " 字节)，低于安全边际"},
        {"GBA_VALIDATION_FAILED", "GBA验证失败 - 切割点后可能有重要数据"},
        {"NDS_VALIDATION_FAILED", "NDS验证失败 - ARM9/ARM7偏移可能无效"},
        {"GB_VALIDATION_FAILED", "GB/GBC验证失败 - ROM结构可能受损"},
        {"CUT_TOO_LARGE_UNKNOWN_ROM", "对未知ROM类型的削减过大"},
        {"CUT_INTERRUPTS_KNOWN_STRUCTURES", "削减将中断已知的ROM结构"},
        {"FORCE_HELP", "强制不安全操作"},
        {"EXAMPLE_TRIM_SINGLE", "修剪单个文件: romtrimmer++ -i game.gba"},
        {"EXAMPLE_PROCESS_DIR", "处理目录: romtrimmer++ -p roms/ -r -o trimmed/"},
        {"EXAMPLE_ANALYZE_ONLY", "仅分析: romtrimmer++ -i game.nds --analyze"},
        {"VERSION_TEXT", "RomTrimmer++ v1.0.0\n"},
        {"VALIDATION_OK", "确定"},
        {"HIGH_RISK_OPERATION", "高风险操作: "},
        {"VALIDATION_EXCEPTION", "验证异常: "},
        {"EMPTY_DATA", "提供了空数据"},
        {"LARGE_CUT_WARNING", "检测到大削减 ("},
        {"SUGGEST_FORCE_OR_ANALYZE", "考虑先使用 --analyze 或 --force 如果确定"},
        {"HEADER_INTEGRITY_COMPROMISED", "ROM头完整性将受损"},
        {"SUGGEST_BACKUP_AND_VERIFY", "创建备份并在修剪后验证ROM功能"},
        {"RISK_LARGE_CUT", "大削减 ("},
        {"RISK_BELOW_RECOMMENDED", "大小低于推荐最小值"},
        {"RISK_STRUCTURE_CONFLICT", "削减将影响已知数据结构"},
        {"RECOMMENDATION_LOW_RISK", "低风险操作，正常进行"},
        {"RECOMMENDATION_MEDIUM_RISK", "中等风险，考虑先使用 --analyze"},
        {"RECOMMENDATION_HIGH_RISK", "高风险，仅在绝对确定时使用 --force"},
        {"RECOMMENDATION_CRITICAL_RISK", "严重风险，不推荐操作"},
        {"INTERRUPT_RECEIVED", "操作被用户中断"},
        {"SEGMENTATION_FAULT", "检测到段错误"},
        {"PLEASE_REPORT_BUG", "请在项目仓库报告此问题"},
        {"TERMINATION_REQUESTED", "请求终止，正在清理..."},
        {"LANGUAGE_SET", "语言已设置为"},
        {"LANGUAGE_ERROR", "语言配置错误"},
        {"FALLBACK_TO_ENGLISH", "回退到英语"},
        {"QUICK_EXAMPLES", "快速示例"},
        {"TROUBLESHOOTING_TIPS", "故障排除提示"},
        {"CHECK_PERMISSIONS", "检查文件和目录权限"},
        {"VERIFY_INPUT_FILES", "验证输入文件是否为有效的ROM"},
        {"TRY_DRY_RUN_FIRST", "先使用 --dry-run 尝试查看会发生什么"},
        {"REPORT_ISSUE", "在项目仓库报告此问题并提供详细信息"},
        {"NO_BACKUP_HELP", "不创建备份文件"},
        {"ARGUMENT_ERROR", "参数解析错误"},
        {"INVALID_OUTPUT_DIR", "无效的输出目录"},
        {"HIGH_CUT_RATIO_WARNING", "警告: 最大削减比率非常高"},
        {"SUCCESSFULLY_TRIMMED", "成功修剪"},
        {"NO_CHANGES", "未进行任何更改"},
        {"SUPPORTED_FORMATS", "支持的格式"},
        {"SAFETY_NOTES", "安全说明"}
    };
}